SELECT
    PHJD.PHJD_KHA_COD AS KHA_COD,
    SelectedSKMD.SKMD_SZK_COD AS SZK_COD,
    PHJD.PHJD_KM_COD AS KM_COD,
    PHJD.PHJD_TAS_YDO AS TAS_YDO,
    SelectedPPJD.PPJD_KM_COD AS IRS_KM_COD,
    SelectedSKMD.SKMD_SZK_COD AS IRS_SZK_COD,
    SUM(NVL(PHJD.PHJD_4M_JSC, 0)) AS JSC_04M,
    SUM(NVL(PHJD.PHJD_5M_JSC, 0)) AS JSC_05M,
    SUM(NVL(PHJD.PHJD_6M_JSC, 0)) AS JSC 06M,
    SUM(NVL(PHJD.PHJD_7M_JSC, 0)) AS JSC 07M,
    SUM(NVL(PHJD.PHJD_8M_JSC, 0)) AS JSC 08M,
    SUM(NVL(PHJD.PHJD_9M_JSC, 0)) AS JSC 09M,
    SUM(NVL(PHJD.PHJD_10M_JSC, 0)) AS JSC 10M,
    SUM(NVL(PHJD.PHJD_11M_JSC, 0)) AS JSC 11M,
    SUM(NVL(PHJD.PHJD_12M_JSC, 0)) AS JSC 12M,
    SUM(NVL(PHJD.PHJD_1M_JSC, 0)) AS JSC 01M,
    SUM(NVL(PHJD.PHJD_2M_JSC, 0)) AS JSC 02M,
    SUM(NVL(PHJD.PHJD_3M_JSC, 0)) AS JSC 03M
FROM
    BGTA2_PHJD PHJD
INNER JOIN
    (SELECT DISTINCT PPJD_KHA_COD, PPJD_KM_COD
     FROM BGTA3_PPJD
     WHERE PPJD_KHA_COD = '20512'
       AND PPJD_IRM_PJ_COD IS NOT NULL) SelectedPPJD
    ON SelectedPPJD.PPJD_KHA_COD = PHJD.PHJD_KHA_COD
    AND SelectedPPJD.PPJD_KM_COD = PHJD.PHJD_KM_COD  -- 确保与PHJD表中的KM_COD匹配
INNER JOIN
    (SELECT DISTINCT SKMD_KHA_COD, SKMD_KM_COD, SKMD_SZK_COD
     FROM BGTA2_SKMD
     WHERE SKMD_KHA_COD = '20512'
       AND SKMD_KBS_VER_ID = '60') SelectedSKMD
    ON SelectedSKMD.SKMD_KHA_COD = PHJD.PHJD_KHA_COD
    AND SelectedSKMD.SKMD_KM_COD = PHJD.PHJD_KM_COD  -- 确保与PHJD表中的KM_COD匹配
WHERE
    PHJD.PHJD_KHA_COD = '20512'
    AND PHJD.PHJD_TAS_YDO = '2023'
    AND PHJD.PHJD_GHM_LV1_COD = '52'
    AND PHJD.PHJD_YSS_DTK_COD = '9'
    AND PHJD.PHJD_YSS_DTB_COD = '92'
    AND EXISTS (
        SELECT 1
        FROM BGTAZ_PTCD PTCD
        WHERE PTCD.PTCD_KHA_COD = PHJD.PHJD_KHA_COD
        AND PTCD.PTCD_PJ_COD = PHJD.PHJD_PJ_COD
    )
GROUP BY
    PHJD.PHJD_KHA_COD,
    SelectedSKMD.SKMD_SZK_COD,
    PHJD.PHJD_KM_COD,
    PHJD.PHJD_TAS_YDO,
    SelectedPPJD.PPJD_KM_COD,
    SelectedSKMD.SKMD_SZK_COD
ORDER BY
    PHJD.PHJD_KHA_COD,
    SelectedSKMD.SKMD_SZK_COD,
    PHJD.PHJD_KM_COD,
    PHJD.PHJD_TAS_YDO;
