SELECT
    PHJD_KHA_COD AS KHA_COD,
    SKMD_SZK_COD AS SZK_COD,
    PHJD_KM_COD AS KM_COD,
    PHJD_TAS_YDO AS TAS_YDO,
    IRS_KM_COD,
    IRS_SZK_COD,
    SUM(NVL(JSC_04M, 0)) AS JSC_04M,
    SUM(NVL(JSC_05M, 0)) AS JSC_05M,
    SUM(NVL(JSC_06M, 0)) AS JSC_06M,
    SUM(NVL(JSC_07M, 0)) AS JSC_07M,
    SUM(NVL(JSC_08M, 0)) AS JSC_08M,
    SUM(NVL(JSC_09M, 0)) AS JSC_09M,
    SUM(NVL(JSC_10M, 0)) AS JSC_10M,
    SUM(NVL(JSC_11M, 0)) AS JSC_11M,
    SUM(NVL(JSC_12M, 0)) AS JSC_12M,
    SUM(NVL(JSC_01M, 0)) AS JSC_01M,
    SUM(NVL(JSC_02M, 0)) AS JSC_02M,
    SUM(NVL(JSC_03M, 0)) AS JSC_03M
FROM
    (SELECT
        PHJD.PHJD_KHA_COD AS PHJD_KHA_COD,
        SKMD.SKMD_SZK_COD AS SKMD_SZK_COD,
        PHJD.PHJD_KM_COD AS PHJD_KM_COD,
        PHJD.PHJD_TAS_YDO AS PHJD_TAS_YDO,
        PPJD.PPJD_KM_COD AS IRS_KM_COD,
        SKMD.SKMD_SZK_COD AS IRS_SZK_COD,
        PHJD.PHJD_4M_JSC AS JSC_04M,
        PHJD.PHJD_5M_JSC AS JSC_05M,
        PHJD.PHJD_6M_JSC AS JSC_06M,
        PHJD.PHJD_7M_JSC AS JSC_07M,
        PHJD.PHJD_8M_JSC AS JSC_08M,
        PHJD.PHJD_9M_JSC AS JSC_09M,
        PHJD.PHJD_10M_JSC AS JSC_10M,
        PHJD.PHJD_11M_JSC AS JSC_11M,
        PHJD.PHJD_12M_JSC AS JSC_12M,
        PHJD.PHJD_1M_JSC AS JSC_01M,
        PHJD.PHJD_2M_JSC AS JSC_02M,
        PHJD.PHJD_3M_JSC AS JSC_03M
    FROM
        BGTA2_PHJD PHJD
    INNER JOIN
        BGTA3_PPJD PPJD ON PPJD.PPJD_KHA_COD = PHJD.PHJD_KHA_COD
            AND PPJD.PPJD_PJ_COD = PHJD.PHJD_IRS_PJ_COD
            AND PPJD.PPJD_IRM_PJ_COD = PHJD.PHJD_PJ_COD
    INNER JOIN
        BGTA2_SKMD SKMD ON SKMD.SKMD_KHA_COD = PHJD.PHJD_KHA_COD
            AND SKMD.SKMD_KM_COD = PHJD.PHJD_KM_COD
            AND SKMD.SKMD_KBS_VER_ID = '60'
    WHERE
        PHJD.PHJD_KHA_COD = '20512'
        AND PHJD.PHJD_TAS_YDO = '2023'
        AND PHJD.PHJD_GHM_LV1_COD = '52'
        AND PHJD.PHJD_YSS_DTK_COD = '9'
        AND PHJD.PHJD_YSS_DTB_COD = '92'
        AND EXISTS (
            SELECT 1
            FROM BGTAZ_PTCD PTCD
            WHERE PTCD.PTCD_KHA_COD = PHJD.PHJD_KHA_COD
                AND PTCD.PTCD_PJ_COD = PHJD.PHJD_PJ_COD
        )
    ) A
INNER JOIN
    (SELECT
        SKMD_KHA_COD,
        SKMD_KM_COD,
        SKMD_SZK_COD AS IRS_SZK_COD
    FROM
        BGTA2_SKMD
    WHERE
        SKMD_KHA_COD = '20512' AND SKMD_KBS_VER_ID = '60'
    ) B ON A.PHJD_KHA_COD = B.SKMD_KHA_COD
        AND A.PHJD_KM_COD = B.SKMD_KM_COD
GROUP BY
    PHJD_KHA_COD,
    SKMD_SZK_COD,
    PHJD_KM_COD,
    PHJD_TAS_YDO,
    IRS_KM_COD,
    IRS_SZK_COD
ORDER BY
    PHJD_KHA_COD,
    SKMD_SZK_COD,
    PHJD_KM_COD,
    PHJD_TAS_YDO;
