/*SQLクエリの改善についての説明を日本語で提供します。以下の最適化されたクエリは、可読性と効率性を高めるためのものです。*/
SELECT
    A.KHA_COD,
    A.SZK_COD,
    A.KM_COD,
    A.TAS_YDO,
    A.IRS_KM_COD,
    B.IRS_SZK_COD,
    SUM(A.JSC_04M) AS JSC_04M,
    SUM(A.JSC_05M) AS JSC_05M,
    SUM(A.JSC_06M) AS JSC_06M,
    SUM(A.JSC_07M) AS JSC_07M,
    SUM(A.JSC_08M) AS JSC_08M,
    SUM(A.JSC_09M) AS JSC_09M,
    SUM(A.JSC_10M) AS JSC_10M,
    SUM(A.JSC_11M) AS JSC_11M,
    SUM(A.JSC_12M) AS JSC_12M,
    SUM(A.JSC_01M) AS JSC_01M,
    SUM(A.JSC_02M) AS JSC_02M,
    SUM(A.JSC_03M) AS JSC_03M
FROM
    (
        SELECT
            PHJD.PHJD_KHA_COD AS KHA_COD,
            SKMD.SKMD_SZK_COD AS SZK_COD,
            PHJD.PHJD_KM_COD AS KM_COD,
            PHJD.PHJD_TAS_YDO AS TAS_YDO,
            PPJD.PPJD_KM_COD AS IRS_KM_COD,
            NVL(PHJD.PHJD_4M_JSC, 0) AS JSC_04M,
            NVL(PHJD.PHJD_5M_JSC, 0) AS JSC_05M,
            NVL(PHJD.PHJD_6M_JSC, 0) AS JSC_06M,
            NVL(PHJD.PHJD_7M_JSC, 0) AS JSC_07M,
            NVL(PHJD.PHJD_8M_JSC, 0) AS JSC_08M,
            NVL(PHJD.PHJD_9M_JSC, 0) AS JSC_09M,
            NVL(PHJD.PHJD_10M_JSC, 0) AS JSC_10M,
            NVL(PHJD.PHJD_11M_JSC, 0) AS JSC_11M,
            NVL(PHJD.PHJD_12M_JSC, 0) AS JSC_12M,
            NVL(PHJD.PHJD_1M_JSC, 0) AS JSC_01M,
            NVL(PHJD.PHJD_2M_JSC, 0) AS JSC_02M,
            NVL(PHJD.PHJD_3M_JSC, 0) AS JSC_03M
        FROM
            BGTA2_PHJD PHJD
            JOIN BGTA3_PPJD PPJD ON PHJD.PHJD_KHA_COD = PPJD.PPJD_KHA_COD
                AND PHJD.PHJD_IRS_PJ_COD = PPJD.PPJD_PJ_COD
                AND PHJD.PHJD_PJ_COD = PPJD.PPJD_IRM_PJ_COD
            JOIN BGTA2_SKMD SKMD ON PHJD.PHJD_KHA_COD = SKMD.SKMD_KHA_COD
                AND PHJD.PHJD_KM_COD = SKMD.SKMD_KM_COD
                AND SKMD.SKMD_KBS_VER_ID = 60
        WHERE
            PHJD.PHJD_KHA_COD = '20512'
            AND PHJD.PHJD_TAS_YDO = '2023'
            AND PHJD.PHJD_YSS_DTK_COD = '9'
            AND PHJD.PHJD_YSS_DTB_COD = '92'
            AND PHJD.PHJD_GHM_LV1_COD = '52'
            AND EXISTS (
                SELECT 1
                FROM BGTAZ_PTCD PTCD
                WHERE PTCD.PTCD_KHA_COD = PHJD.PHJD_KHA_COD
                    AND PTCD.PTCD_PJ_COD = PHJD.PHJD_PJ_COD
            )
    ) A
JOIN
    (
        SELECT
            SKMD.SKMD_KHA_COD AS KHA_COD,
            SKMD.SKMD_KM_COD AS KM_COD,
            SKMD.SKMD_SZK_COD AS IRS_SZK_COD
        FROM
            BGTA2_SKMD SKMD
        WHERE
            SKMD.SKMD_KHA_COD = '20512'
            AND SKMD.SKMD_KBS_VER_ID = 60
    ) B ON A.KHA_COD = B.KHA_COD AND A.IRS_KM_COD = B.KM_COD
GROUP BY
    A.KHA_COD,
    A.SZK_COD,
    A.KM_COD,
    A.TAS_YDO,
    A.IRS_KM_COD,
    B.IRS_SZK_COD
ORDER BY
    A.KHA_COD,
    A.SZK_COD,
    A.KM_COD,
    A.TAS_YDO;
